---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-helloworld-deployment
spec:
  selector:
    matchLabels:
      app: nginx-helloworld
  replicas: 2 # tells deployment to run 2 pods matching the template - @Jeffrey Solomon Chijioke-uche(MSIT,MSIS, United States)
  template:
    metadata:
      labels:
        app: nginx-helloworld
    spec:
      containers:
      - name: nginx-helloworld
        image: docker.io/jchijiok/helloworld:v1.0.0
        ports:
        - containerPort: 80